// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzxz_39G70peEYTxoS9wxafFxLSzrJWZE',
    appId: '1:151156847487:web:6580bae2bc187bb0ad604a',
    messagingSenderId: '151156847487',
    projectId: 'auth-test-a6a61',
    authDomain: 'auth-test-a6a61.firebaseapp.com',
    storageBucket: 'auth-test-a6a61.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5ukLg_6IXfPMOHDPWjODC2dvuwNymwBY',
    appId: '1:151156847487:android:17cd7678a2c53eeead604a',
    messagingSenderId: '151156847487',
    projectId: 'auth-test-a6a61',
    storageBucket: 'auth-test-a6a61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHJmGmAgd44DYMwxU47Z3CSMbU0BhcPCM',
    appId: '1:151156847487:ios:b3f128c7cd7a5366ad604a',
    messagingSenderId: '151156847487',
    projectId: 'auth-test-a6a61',
    storageBucket: 'auth-test-a6a61.appspot.com',
    iosClientId: '151156847487-a7ku0djcgie4l2amfkikg1gpnucujgee.apps.googleusercontent.com',
    iosBundleId: 'com.example.authTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHJmGmAgd44DYMwxU47Z3CSMbU0BhcPCM',
    appId: '1:151156847487:ios:b3f128c7cd7a5366ad604a',
    messagingSenderId: '151156847487',
    projectId: 'auth-test-a6a61',
    storageBucket: 'auth-test-a6a61.appspot.com',
    iosClientId: '151156847487-a7ku0djcgie4l2amfkikg1gpnucujgee.apps.googleusercontent.com',
    iosBundleId: 'com.example.authTest',
  );
}
